name: 'Minecraft Version Manifest Info'
description: 'A GitHub action to get infos about Minecraft version manifest.'
author: 'Mqxx'
inputs:
  manifest-url:
    description: 'An URL to the version manifest.'
    default: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
    required: false
  token:
    description: 'GitHub token.'
    required: true

outputs:
  version-current-release:
    description: 'The current Minecraft release version fetched.'

  version-current-snapshot:
    description: 'The current Minecraft snapshot version fetched.'

  version-previous-release:
    description: 'The previous Minecraft release version fetched.'

  version-previous-snapshot:
    description: 'The previous Minecraft snapshot version fetched.'

runs:
  using: 'node20'
  main: 'dist/bundle.min.js'
