name: 'Minecraft Version Manifest Info'
description: 'A GitHub action to get infos about Minecraft version manifest.'
author: 'Mqxx'
inputs:
  token:
    description: 'GitHub token.'
    required: true

  manifest-url:
    description: 'An URL to the version manifest.'
    default: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
    required: false

outputs:
  version-changed:
    description: 'Whether the release or snapshot version has changed.'

  version-release-changed:
    description: 'Whether the release version has changed.'
  
  version-snapshot-changed:
    description: 'Whether the snapshot version has changed.'

  version-current-release:
    description: 'The current Minecraft release version fetched.'

  version-current-snapshot:
    description: 'The current Minecraft snapshot version fetched.'

  version-previous-release:
    description: 'The previous Minecraft release version from artifact.'

  version-previous-snapshot:
    description: 'The previous Minecraft snapshot version from artifact.'
  

runs:
  using: 'node20'
  main: 'dist/bundle.min.js'
