name: 'Build'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: Setup Deno (${{env.deno-version}})
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: ${{env.deno-version}}

      - name: Bundle
        run: deno task build
