name: 'Test Latest Build Action'

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  test:
    name: 'Test Action'
    runs-on: ubuntu-latest      

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Test Action'
        id: 'test-action'
        uses: Datapack-Registry/minecraft-manifest@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      
      - name: 'Print'
        run: |
          echo "version-changed: ${{steps.test-action.outputs.version-changed}}"
          echo "version-release-changed: ${{steps.test-action.outputs.version-release-changed}}"
          echo "version-snapshot-changed: ${{steps.test-action.outputs.version-snapshot-changed}}"

          echo "version-previous-release: ${{steps.test-action.outputs.version-previous-release}}"
          echo "version-previous-snapshot: ${{steps.test-action.outputs.version-previous-snapshot}}"
          echo "version-current-release: ${{steps.test-action.outputs.version-current-release}}"
          echo "version-current-release-url: ${{steps.test-action.outputs.version-current-release-url}}"
          echo "version-current-snapshot: ${{steps.test-action.outputs.version-current-snapshot}}"
          echo "version-current-snapshot-url: ${{steps.test-action.outputs.version-current-snapshot-url}}"
