name: 'Test Action'

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: 'Test Action'
    runs-on: ubuntu-latest
    env:
      deno-version: v1.x

    steps:
      - name: 'Setup Repository (${{github.event.repository.name}})'
        uses: actions/checkout@v4
      
      - name: 'Test Action'
        uses: Datapack-Registry/minecraft-manifest@main
        with:
          manifest-url: 'Test123'
